# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bcf8766e94a6c952b924a300e650a6fefa561dcb29289c797588057ad8a8f7577d701309d5e8e1a73c8b38bcddee75a585856289cd96b87a24215bbbcc7fe99

test:
  secret_key_base: 42b905af42b57bc1be6584dcf2acce1aa5040fb58416f67a431397036b7ad8fba19d4593a320508004f84986c5486c68df8e26b9c28d20d15df8c822b4ad4e70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
